---
deployment:
  tasks:
    - composer install --no-dev --optimize-autoloader
    - php artisan migrate --force
    - php artisan config:clear
    - php artisan route:clear
    - php artisan view:clear
    - php artisan storage:link
